/**
 * Specs Routes for ZeroToShip API
 *
 * Endpoints:
 * - GET /api/v1/specs - List user's generated specs
 * - GET /api/v1/specs/:id - Get a single spec with full detail
 */

import { FastifyPluginAsync } from 'fastify';
import { ZodTypeProvider } from 'fastify-type-provider-zod';
import { z } from 'zod';
import { requireAuth } from '../middleware/auth';
import { db, specGenerations, ideas } from '../db/client';
import { eq, and, desc, sql } from 'drizzle-orm';
import { ApiErrorSchema } from '../schemas';

export const specsRoutes: FastifyPluginAsync = async (fastify) => {
  const app = fastify.withTypeProvider<ZodTypeProvider>();

  /**
   * GET /api/v1/specs
   * List all specs generated by the authenticated user
   */
  app.get(
    '/',
    {
      preHandler: [requireAuth],
      schema: {
        querystring: z.object({
          page: z.coerce.number().int().positive().default(1),
          limit: z.coerce.number().int().min(1).max(100).default(20),
        }),
        response: {
          200: z.object({
            specs: z.array(
              z.object({
                id: z.string().uuid(),
                ideaId: z.string().uuid(),
                ideaName: z.string(),
                projectName: z.string(),
                createdAt: z.string(),
              })
            ),
            total: z.number(),
            page: z.number(),
            limit: z.number(),
          }),
        },
      },
    },
    async (request, reply) => {
      const { page, limit } = request.query;
      const offset = (page - 1) * limit;

      const [rows, totalRows] = await Promise.all([
        db
          .select({
            id: specGenerations.id,
            ideaId: specGenerations.ideaId,
            ideaName: ideas.name,
            spec: specGenerations.spec,
            createdAt: specGenerations.createdAt,
          })
          .from(specGenerations)
          .innerJoin(ideas, eq(specGenerations.ideaId, ideas.id))
          .where(eq(specGenerations.userId, request.userId!))
          .orderBy(desc(specGenerations.createdAt))
          .limit(limit)
          .offset(offset),
        db
          .select({ count: sql<number>`count(*)::int` })
          .from(specGenerations)
          .where(eq(specGenerations.userId, request.userId!)),
      ]);

      const specs = rows.map((row) => ({
        id: row.id,
        ideaId: row.ideaId,
        ideaName: row.ideaName,
        projectName: (row.spec as { projectName?: string })?.projectName || row.ideaName,
        createdAt: row.createdAt.toISOString(),
      }));

      return reply.send({
        specs,
        total: totalRows[0].count,
        page,
        limit,
      });
    }
  );

  /**
   * GET /api/v1/specs/:id
   * Get a single spec with full detail
   */
  app.get(
    '/:id',
    {
      preHandler: [requireAuth],
      schema: {
        params: z.object({
          id: z.string().uuid(),
        }),
        response: {
          200: z.object({
            id: z.string().uuid(),
            ideaId: z.string().uuid(),
            ideaName: z.string(),
            projectName: z.string(),
            spec: z.unknown(),
            createdAt: z.string(),
          }),
          404: ApiErrorSchema,
        },
      },
    },
    async (request, reply) => {
      const { id } = request.params;

      const rows = await db
        .select({
          id: specGenerations.id,
          userId: specGenerations.userId,
          ideaId: specGenerations.ideaId,
          ideaName: ideas.name,
          spec: specGenerations.spec,
          createdAt: specGenerations.createdAt,
        })
        .from(specGenerations)
        .innerJoin(ideas, eq(specGenerations.ideaId, ideas.id))
        .where(
          and(
            eq(specGenerations.id, id),
            eq(specGenerations.userId, request.userId!)
          )
        )
        .limit(1);

      if (rows.length === 0) {
        return reply.status(404).send({
          code: 'NOT_FOUND',
          message: 'Spec not found',
        });
      }

      const row = rows[0];

      return reply.send({
        id: row.id,
        ideaId: row.ideaId,
        ideaName: row.ideaName,
        projectName: (row.spec as { projectName?: string })?.projectName || row.ideaName,
        spec: row.spec,
        createdAt: row.createdAt.toISOString(),
      });
    }
  );
};
